server:
  host: "0.0.0.0"
  port: 8080
  reload: true
encoder:
  name: "sentence-transformers/all-mpnet-base-v2"
  device: "auto"
  normalize_input: false
axes:
  k_max: 32
  aggregator: "linear"
  beta_mix: 0.5
  lambda: 1.0
  beta: 0.0
  weights: "uniform"
coherence:
  window: 64
  max_pairs_per_token: 12
  sigma_mode: "median"
  seed: 17
diffusion:
  taus: [0.0, 0.6]
  implicit_steps: 3
  alpha_mode: "tau_over_steps"
spans:
  max_tokens: 700
  score_threshold: 0.35
  prefilter_topk: 48
api:
  max_doc_chars: 100000

# --- Added for Agent/Search integration ---
agent_api:
  enabled: true

index:
  tokenizer: "simple_split"   # TODO(@builder): spaCy later
  span_window: 64
  span_stride: 32
  taus: [0.0, 0.6]
  prefilter_topk: 48
  seed: 17

ann:
  backend: "hnsw"            # "hnsw" | "numpy"
  space: "l2"
  ef_construction: 200
  M: 32

search:
  squash: true                # apply sigmoid to utilities
  beta: 0.3                   # coherence vs resonance
  alpha: 0.5                  # gated utility vs align/prox
  gamma: 0.6                  # coverage vs proximity
  minC: 0.0                   # default coherence filter
  tau: 0.0                    # default diffusion scale
