version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: "%(asctime)s %(levelname)s %(name)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  coherence:
    level: DEBUG
    handlers: [console]
    propagate: no
  uvicorn:
    level: DEBUG
    handlers: [console]
    propagate: no
  fastapi:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
