name: CI

on:
  push:
  pull_request:

permissions:
  contents: read
  actions: read

jobs:
  quality:
    name: Lint • Typecheck • Test • OpenAPI • Smoke
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black mypy pytest pytest-cov

      - name: Ruff
        run: ruff check src

      - name: Black (check only)
        run: black --check src

      - name: Mypy
        run: mypy src

      - name: Pytest (with coverage)
        # Set to 'true' later to hard-fail. During rollout you can allow failures:
        # continue-on-error: true
        run: |
          pytest -q --maxfail=1 --disable-warnings \
                 --cov=src --cov-report=term-missing:skip-covered \
                 --cov-report=xml:coverage.xml

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

      - name: Export OpenAPI
        run: |
          mkdir -p docs
          python scripts/export_openapi.py --out docs/openapi.json

      - name: Upload OpenAPI artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi
          path: docs/openapi.json

      - name: Boot API (background)
        run: uvicorn coherence.api.main:app --host 0.0.0.0 --port 8000 &

      - name: Smoke /health/ready
        run: |
          sleep 5
          curl -f http://localhost:8000/health/ready

      - name: Smoke /v1/eval/text
        run: |
          curl -sS -X POST http://localhost:8000/v1/eval/text \
            -H "Content-Type: application/json" \
            -d '{"text":"hello ethical world","window":8,"stride":4}' | jq .proof.final.action

      - name: Smoke /v1/interaction/respond
        run: |
          curl -sS -X POST http://localhost:8000/v1/interaction/respond \
            -H "Content-Type: application/json" \
            -d '{"prompt":"Suggest productive study habits"}' | jq .final
