name: CI
on:
  push:
    branches: [ main, harden/** ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Lint
        run: |
          pip install ruff pytest || pip install flake8 pytest
          if (Test-Path ruff.toml) { ruff check . } else { flake8 . }
      - name: Tests
        run: pytest -q
      - name: Export OpenAPI
        run: if (Test-Path scripts/export_openapi.py) { python scripts/export_openapi.py -o docs/openapi.json }
      - name: Upload OpenAPI
        if: success() && (hashFiles('docs/openapi.json') != '')
        uses: actions/upload-artifact@v4
        with: { name: openapi, path: docs/openapi.json }
