name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install -r requirements.txt
    - run: pip install ruff black mypy
    - run: ruff check src
    - run: black --check src
    - run: mypy src
    - run: pytest -q
    - name: Install coverage
      run: pip install coverage
    - name: Run tests with coverage
      run: pytest -q --cov=src --cov-report=xml
    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
    - run: python scripts/export_openapi.py
    - uses: actions/upload-artifact@v4
      with:
        name: openapi
        path: docs/openapi.json
    - run: uvicorn coherence.api.main:app --host 0.0.0.0 --port 8000 &
    - run: sleep 10
    - run: curl -f http://localhost:8000/health/ready
    - run: |
        curl -X POST http://localhost:8000/pipeline/analyze -H "Content-Type: application/json" -d '{"text": "test"}'
