name: CI

on:
  push:
    branches: [ main, harden/** ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Lint (ruff if present, else flake8)
        run: |
          if (Test-Path .\ruff.toml) { pip install ruff; ruff check . } else { pip install flake8; flake8 . }
      - name: Tests
        run: |
          pip install pytest
          pytest -q
      - name: Export OpenAPI (if script exists)
        run: |
          if (Test-Path .\scripts\export_openapi.py) { python .\scripts\export_openapi.py -o .\docs\openapi.json }
      - name: Upload OpenAPI
        if: success() && (hashFiles('docs/openapi.json') != '')
        uses: actions/upload-artifact@v4
        with:
          name: openapi
          path: docs/openapi.json
